=== RafaGomezGuillen/desarrollo-de-aplicaciones-web/LND/ejercicios_xml/actividad_08/personas.dtd
<!ELEMENT personas (persona+)>
<!ELEMENT persona (nombre, nacimiento?, direccion+, (varon | hembra))>
<!ELEMENT nombre (#PCDATA)>
<!ELEMENT nacimiento EMPTY>
<!ATTLIST nacimiento dia NMTOKEN #REQUIRED>
<!ATTLIST nacimiento mes CDATA #REQUIRED>
<!ATTLIST nacimiento anyo NMTOKEN #REQUIRED>
<!ELEMENT direccion (calle, poblacion, provincia, cpostal)>
<!ELEMENT calle (#PCDATA)>
<!ELEMENT poblacion (#PCDATA)>
<!ELEMENT provincia (#PCDATA)>
<!ELEMENT cpostal (#PCDATA)>
<!ELEMENT varon EMPTY>
<!ELEMENT hembra EMPTY>

=== RafaGomezGuillen/desarrollo-de-aplicaciones-web/LND/ejercicios_xml/actividad_08/personas_externo.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE personas SYSTEM "personas.dtd">

<personas>
  <persona>
    <nombre>Juan Pardo</nombre>
    <nacimiento dia="10" mes="Abril" anyo="1982" />
    <direccion>
      <calle>caoba, 1</calle>
      <poblacion>Madrid</poblacion>
      <provincia>Madrid</provincia>
      <cpostal>28005</cpostal>
    </direccion>
    <varon />
  </persona>
  <persona>
    <nombre>Sandra Pardo</nombre>
    <direccion>
      <calle>caoba, 1</calle>
      <poblacion>Madrid</poblacion>
      <provincia>Madrid</provincia>
      <cpostal>28005</cpostal>
    </direccion>
    <direccion>
      <calle>ofra, 2</calle>
      <poblacion>Santa Cruz de Tenerife</poblacion>
      <provincia>Canarias</provincia>
      <cpostal>38005</cpostal>
    </direccion>
    <hembra />
  </persona> 
</personas>
