=== RafaGomezGuillen/desarrollo-de-aplicaciones-web/LND/examenes/Rafael Alejandro Gomez Guillen (xml)/DTD/ejercicio.dtd
<!ELEMENT catalogo (producto+)>
<!ATTLIST producto
  nombre CDATA #IMPLIED
  categoria (herramienta | mesa | tienda-profesional) "herramienta"
  inventario (enstock | bajoorden | tienda-nodisponible) #IMPLIED>
<!ELEMENT producto (especificaciones+, opciones*, fabrica?, precios+, notas*, stock?)>
<!ELEMENT especificaciones (#PCDATA)>
<!ATTLIST especificaciones
  peso CDATA #IMPLIED
  potencia CDATA #REQUIRED>
<!ELEMENT opciones (#PCDATA)>
<!ATTLIST opciones adaptador (incluido | opcional | noincluido) "incluido">
<!ELEMENT fabrica (#PCDATA)>
<!ELEMENT precios (#PCDATA)>
<!ATTLIST precios
  moneda (euros | libra) #IMPLIED
  gastodeenvio CDATA #IMPLIED>
<!ELEMENT notas (#PCDATA)>
<!ELEMENT stock EMPTY>

=== RafaGomezGuillen/desarrollo-de-aplicaciones-web/LND/examenes/Rafael Alejandro Gomez Guillen (xml)/DTD/ejercicio.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE catalogo SYSTEM "ejercicio.dtd">
<catalogo>
	<producto nombre="martillo" categoria="herramienta" inventario="bajoorden">
		<especificaciones peso="34" potencia="45">Especificaciones</especificaciones>
		<opciones adaptador="incluido">Opcion1</opciones>
		<opciones adaptador="opcional">Opcion2</opciones>
		<opciones adaptador="noincluido">Opcion3</opciones>
		<fabrica>Palencia</fabrica>
		<precios moneda="libra" gastodeenvio="55">66.4</precios>
		<notas>Ninguna</notas>
	</producto>
	<producto nombre="mesilla" categoria="mesa">
		<especificaciones potencia="45">Especificaciones</especificaciones>
		<opciones>opcion1</opciones>
		<opciones>Opcion1</opciones>
		<precios>45.6</precios>
		<notas>Nota1</notas>
		<notas>Nota2</notas>
	</producto>
	<producto nombre="tienda-profesional" categoria="herramienta" inventario="bajoorden">
		<especificaciones peso="34" potencia="45">Especificaciones</especificaciones>
		<especificaciones peso="34" potencia="45">Especificaciones</especificaciones>
		<especificaciones peso="34" potencia="45">Especificaciones</especificaciones>
		<precios moneda="libra" gastodeenvio="55">56.7</precios>
		<precios moneda="libra" gastodeenvio="55">87.1</precios>
		<precios moneda="libra" gastodeenvio="55">44.4</precios>
	</producto>
</catalogo>
