=== RafaGomezGuillen/desarrollo-de-aplicaciones-web/LND/ejercicios_xml/actividad_11/ejercicio_03/ejercicio3.xsd
<?xml version="1.0"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">
  <xs:element name="alumnos">
    <xs:complexType>
      <xs:sequence>
        <xs:element name="alumno" maxOccurs="unbounded">
          <xs:complexType>
            <xs:sequence>
              <xs:element name="nombre" type="xs:string" />
              <xs:element name="apellidos" type="xs:string" />
              <xs:element name="nota" type="tipoNota"/>
              <xs:element name="edad" minOccurs="0">
                <xs:simpleType>
                  <xs:restriction base="xs:positiveInteger">
                    <xs:minInclusive value="15"></xs:minInclusive>
                    <xs:maxInclusive value="75"></xs:maxInclusive>
                  </xs:restriction>
                </xs:simpleType>
              </xs:element>
              <xs:element name="comentario" type="xs:string" minOccurs="0" />
              <xs:element name="direccion" minOccurs="0">
                <xs:complexType>
                  <xs:sequence>
                    <xs:element name="calle">
                      <xs:simpleType>
                        <xs:restriction base="xs:string">
                          <xs:maxLength value="25" />
                        </xs:restriction>
                      </xs:simpleType>
                    </xs:element>
                    <xs:element name="numero" type="xs:integer" />
                    <xs:element name="poblacion" type="xs:string" />
                    <xs:element name="codigo-postal">
                      <xs:simpleType>
                        <xs:restriction base="xs:string">
                          <xs:pattern value="\d{5}"></xs:pattern>
                        </xs:restriction>
                      </xs:simpleType>
                    </xs:element>
                  </xs:sequence>
                </xs:complexType>
              </xs:element>
            </xs:sequence>
            <xs:attribute name="dni">
              <xs:simpleType>
                <xs:restriction base="xs:string">
                  <xs:pattern value="\d{7}\d?[A-Z]"></xs:pattern>
                </xs:restriction>
              </xs:simpleType>
            </xs:attribute>
          </xs:complexType>
        </xs:element>
      </xs:sequence>
    </xs:complexType>
  </xs:element>
  <xs:simpleType name="tipoNota">
    <xs:union>
      <xs:simpleType>
        <xs:restriction base="xs:decimal">
          <xs:minInclusive value="0"></xs:minInclusive>
          <xs:maxInclusive value="10"></xs:maxInclusive>
          <xs:fractionDigits value="2"></xs:fractionDigits>
        </xs:restriction>
      </xs:simpleType>
      <xs:simpleType>
        <xs:restriction base="xs:string">
          <xs:enumeration value="No presentado"></xs:enumeration>
        </xs:restriction>
      </xs:simpleType>
    </xs:union>
  </xs:simpleType>
</xs:schema>

=== RafaGomezGuillen/desarrollo-de-aplicaciones-web/LND/ejercicios_xml/actividad_11/ejercicio_03/ejercicio3.xml
<?xml version="1.0" encoding="UTF-8"?>
<alumnos
  xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
  xsi:noNamespaceSchemaLocation="ejercicio3.xsd">
  <alumno dni="99887766X">
    <nombre>Dario</nombre>
    <apellidos>Fernandez Alvarez</apellidos>
    <nota>3.50</nota>
    <edad>45</edad>
    <comentario>Necesita mejorar</comentario>
  </alumno>
  <alumno dni="11223344A">
    <nombre>Luis</nombre>
    <apellidos>Alvarez Garcia</apellidos>
    <nota>6.75</nota>
    <edad>70</edad>
    <comentario>Copio de Dario, Alfredo y Pilar</comentario>
  </alumno>
  <alumno dni="4556677Z">
    <nombre>Pilar</nombre>
    <apellidos>Rodriguez Menendez</apellidos>
    <nota>8.25</nota>
    <comentario>Copio de todos</comentario>
    <direccion>
      <calle>Galiana</calle>
      <numero>23</numero>
      <poblacion>Aviles</poblacion>
      <codigo-postal>33400</codigo-postal>
    </direccion>
  </alumno>
  <alumno dni="99887766X">
    <nombre>Alfredo</nombre>
    <apellidos>Martinez Gonzalez</apellidos>
    <nota>No presentado</nota>
    <comentario>Estudio Universidad de Oviedo</comentario>
    <direccion>
      <calle>Comandante Vallespin</calle>
      <numero>5</numero>
      <poblacion>Oviedo</poblacion>
      <codigo-postal>33021</codigo-postal>
    </direccion>
  </alumno>
</alumnos>
